#**1A) MACHINE LEARNING MODEL**

**A. DATA UNDERSTANDING**

Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, accuracy_score
import pickle

Read Dataset

In [2]:
df = pd.read_csv('/content/Dataset_B_hotel.csv')

Display Dataset

In [3]:
df

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,INN00001,2,0,1,2,Meal Plan 1,0.0,Room_Type 1,224,2017,10,2,Offline,0,0,0,65.00,0,Not_Canceled
1,INN00002,2,0,2,3,Not Selected,0.0,Room_Type 1,5,2018,11,6,Online,0,0,0,106.68,1,Not_Canceled
2,INN00003,1,0,2,1,Meal Plan 1,0.0,Room_Type 1,1,2018,2,28,Online,0,0,0,60.00,0,Canceled
3,INN00004,2,0,0,2,Meal Plan 1,0.0,Room_Type 1,211,2018,5,20,Online,0,0,0,100.00,0,Canceled
4,INN00005,2,0,1,1,Not Selected,0.0,Room_Type 1,48,2018,4,11,Online,0,0,0,94.50,0,Canceled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,INN36271,3,0,2,6,Meal Plan 1,0.0,Room_Type 4,85,2018,8,3,Online,0,0,0,167.80,1,Not_Canceled
36271,INN36272,2,0,1,3,Meal Plan 1,0.0,Room_Type 1,228,2018,10,17,Online,0,0,0,90.95,2,Canceled
36272,INN36273,2,0,2,6,Meal Plan 1,0.0,Room_Type 1,148,2018,7,1,Online,0,0,0,98.39,2,Not_Canceled
36273,INN36274,2,0,0,3,Not Selected,0.0,Room_Type 1,63,2018,4,21,Online,0,0,0,94.50,0,Canceled
36274,INN36275,2,0,1,2,Meal Plan 1,0.0,Room_Type 1,207,2018,12,30,Offline,0,0,0,161.67,0,Not_Canceled

Display Data Type Information in the Dataset

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36275 entries, 0 to 36274
Data columns (total 19 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Booking_ID                            36275 non-null  object
 1   no_of_adults                          36275 non-null  int64
 2   no_of_children                        36275 non-null  int64
 3   no_of_weekend_nights                  36275 non-null  int64
 4   no_of_week_nights                     36275 non-null  int64
 5   type_of_meal_plan                     35368 non-null  object
 6   required_car_parking_space            35005 non-null  float64
 7   room_type_reserved                    36275 non-null  object
 8   lead_time                             36275 non-null  int64
 9   arrival_year                          36275 non-null  int64
 10  arrival_month                         36275 non-null  int64
 11  arrival_date                          36275 non-null  int64
 12  market_segment_type                   36275 non-null  object
 13  repeated_guest                        36275 non-null  int64
 14  no_of_previous_cancellations          36275 non-null  int64
 15  no_of_previous_bookings_not_canceled  36275 non-null  int64
 16  avg_price_per_room                    34643 non-null  float64
 17  no_of_special_requests                36275 non-null  int64
 18  booking_status                        36275 non-null  object
dtypes: float64(2), int64(12), object(5)
memory usage: 5.3+ MB

Display Descriptive Statistics

In [5]:
df.describe()

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,required_car_parking_space,lead_time,arrival_year,arrival_month,arrival_date,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests
count,36275.000000,36275.000000,36275.000000,36275.000000,35005.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,34643.000000,36275.000000
mean,1.844962,0.105279,0.810724,2.204300,0.031281,85.232557,2017.820427,7.423653,15.596995,0.025637,0.023349,0.153411,103.447208,0.619655
std,0.518715,0.402648,0.870644,1.410905,0.174079,85.930817,0.383836,3.069894,8.740447,0.158053,0.368331,1.754171,35.158417,0.786236
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2017.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,0.000000,0.000000,1.000000,0.000000,17.000000,2018.000000,5.000000,8.000000,0.000000,0.000000,0.000000,80.300000,0.000000
50%,2.000000,0.000000,1.000000,2.000000,0.000000,57.000000,2018.000000,8.000000,16.000000,0.000000,0.000000,0.000000,99.450000,0.000000
75%,2.000000,0.000000,2.000000,3.000000,0.000000,126.000000,2018.000000,10.000000,23.000000,0.000000,0.000000,0.000000,120.275000,1.000000
max,4.000000,10.000000,7.000000,17.000000,1.000000,443.000000,2018.000000,12.000000,31.000000,1.000000,13.000000,58.000000,540.000000,5.000000

Check Unique Categories

In [6]:
for col in df.select_dtypes(include=['object']).columns:
    print(f"{col}: {df[col].nunique()} unique categories")

Booking_ID: 36275 unique categories
type_of_meal_plan: 4 unique categories
room_type_reserved: 7 unique categories
market_segment_type: 5 unique categories
booking_status: 2 unique categories

Check Missing Values

In [7]:
missing_values = df.isnull().sum()
print(missing_values)

Booking_ID                                 0
no_of_adults                               0
no_of_children                             0
no_of_weekend_nights                       0
no_of_week_nights                          0
type_of_meal_plan                        907
required_car_parking_space              1270
room_type_reserved                         0
lead_time                                  0
arrival_year                               0
arrival_month                              0
arrival_date                               0
market_segment_type                        0
repeated_guest                             0
no_of_previous_cancellations               0
no_of_previous_bookings_not_canceled       0
avg_price_per_room                      1632
no_of_special_requests                     0
booking_status                             0
dtype: int64

Check Outliers Using IQR

In [8]:
numerical_df = df.select_dtypes(include = ['int64','float'])
Q1 = numerical_df.quantile(0.25)
Q3 = numerical_df.quantile(0.75)
IQR = Q3 - Q1
outliers = (numerical_df < (Q1 - 1.5 * IQR)) | (numerical_df > (Q3 + 1.5 * IQR))
outliers_count = outliers.sum()
print(outliers_count)

no_of_adults                            10167
no_of_children                           2698
no_of_weekend_nights                       21
no_of_week_nights                         324
required_car_parking_space               1095
lead_time                                1331
arrival_year                             6514
arrival_month                               0
arrival_date                                0
repeated_guest                            930
no_of_previous_cancellations              338
no_of_previous_bookings_not_canceled      812
avg_price_per_room                       1614
no_of_special_requests                    761
dtype: int64

**B. DATA PREPARATION**

Handling Missing Values
*   Replace missing values in column 'type_of_meal_plan' with mode
*   Replace missing values in column 'required_car_parking_space' with modus
*   Replace missing values in column 'avg_price_per_room' with median

In [9]:
if 'Booking_ID' in df.columns:
    df = df.drop(columns='Booking_ID')

In [10]:
df['type_of_meal_plan'].fillna(df['type_of_meal_plan'].mode()[0], inplace=True)


df['required_car_parking_space'].fillna(df['required_car_parking_space'].mode()[0], inplace=True)


df['avg_price_per_room'].fillna(df['avg_price_per_room'].median(), inplace=True)

print(df.isnull().sum())

no_of_adults                            0
no_of_children                          0
no_of_weekend_nights                    0
no_of_week_nights                       0
type_of_meal_plan                       0
required_car_parking_space              0
room_type_reserved                      0
lead_time                               0
arrival_year                            0
arrival_month                           0
arrival_date                            0
market_segment_type                     0
repeated_guest                          0
no_of_previous_cancellations            0
no_of_previous_bookings_not_canceled    0
avg_price_per_room                      0
no_of_special_requests                  0
booking_status                          0
dtype: int64

Handling Categorical Features


*   Handle Missing Values in Categorical Column
*   Fill Missing Values With Mode
*   Label encode target (booking_status)
*   Remove 'booking_status' from cat_cols only if it's present
*   Label Encoding for categorical features to reduce memory usage

In [11]:
from sklearn.preprocessing import LabelEncoder


cat_cols = df.select_dtypes(include='object').columns.tolist()


for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])


le = LabelEncoder()
df['booking_status'] = le.fit_transform(df['booking_status'])


if 'booking_status' in cat_cols:
    cat_cols.remove('booking_status')


for col in cat_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36275 entries, 0 to 36274
Data columns (total 18 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   no_of_adults                          36275 non-null  int64
 1   no_of_children                        36275 non-null  int64
 2   no_of_weekend_nights                  36275 non-null  int64
 3   no_of_week_nights                     36275 non-null  int64
 4   type_of_meal_plan                     36275 non-null  int64
 5   required_car_parking_space            36275 non-null  float64
 6   room_type_reserved                    36275 non-null  int64
 7   lead_time                             36275 non-null  int64
 8   arrival_year                          36275 non-null  int64
 9   arrival_month                         36275 non-null  int64
 10  arrival_date                          36275 non-null  int64
 11  market_segment_type                   36275 non-null  int64
 12  repeated_guest                        36275 non-null  int64
 13  no_of_previous_cancellations          36275 non-null  int64
 14  no_of_previous_bookings_not_canceled  36275 non-null  int64
 15  avg_price_per_room                    36275 non-null  float64
 16  no_of_special_requests                36275 non-null  int64
 17  booking_status                        36275 non-null  int64
dtypes: float64(2), int64(16)
memory usage: 5.0 MB

Handling Outliers
*   Fill missing values with median & apply IQR clipping
*   Fill missing values in categorical columns with mode

In [12]:
cols_with_outliers = [
    'no_of_adults', 'no_of_children', 'no_of_weekend_nights', 'no_of_week_nights',
    'required_car_parking_space', 'lead_time', 'no_of_previous_cancellations',
    'no_of_previous_bookings_not_canceled', 'avg_price_per_room', 'no_of_special_requests'
]

for col in cols_with_outliers:
    if df[col].isnull().sum() > 0:
        median_val = np.nanmedian(df[col])
        df[col] = df[col].fillna(median_val)
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    df[col] = df[col].clip(lower=lower, upper=upper)

cat_cols = df.select_dtypes(include='object').columns.tolist()
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

Display Number of Outliers After Winsorizing

In [13]:
remaining_outliers = {}

for col in cols_with_outliers:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    outlier_count = ((df[col] < lower) | (df[col] > upper)).sum()
    remaining_outliers[col] = outlier_count


print("Number of outliers after winsorizing:")
print(pd.Series(remaining_outliers))

Number of outliers after winsorizing:
no_of_adults                            0
no_of_children                          0
no_of_weekend_nights                    0
no_of_week_nights                       0
required_car_parking_space              0
lead_time                               0
no_of_previous_cancellations            0
no_of_previous_bookings_not_canceled    0
avg_price_per_room                      0
no_of_special_requests                  0
dtype: int64

**C. MACHINE LEARNING MODEL**

Seperate Feature & Target and Split Train & Test

In [14]:
X = df.drop('booking_status', axis=1)
y = df['booking_status']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Random Forest Model

In [15]:
rf_model = RandomForestClassifier(n_estimators=10, random_state=42)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)
rf_acc = accuracy_score(y_test, rf_pred)

print("Random Forest Accuracy:", rf_acc)
print("\nClassification Report - Random Forest")
print(classification_report(y_test, rf_pred))

Random Forest Accuracy: 0.8926257753273604

Classification Report - Random Forest
              precision    recall  f1-score   support

           0       0.84      0.83      0.84      2416
           1       0.92      0.92      0.92      4839

    accuracy                           0.89      7255
   macro avg       0.88      0.88      0.88      7255
weighted avg       0.89      0.89      0.89      7255

XGBoost Model

In [16]:
xgb_model = XGBClassifier(
    use_label_encoder=False,
    eval_metric='logloss',
    random_state=42,
    n_jobs=2,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8
    )
xgb_model.fit(X_train, y_train)
xgb_pred = xgb_model.predict(X_test)
xgb_acc = accuracy_score(y_test, xgb_pred)

print("XGBoost Accuracy:", xgb_acc)
print("\nClassification Report - XGBoost")
print(classification_report(y_test, rf_pred))

XGBoost Accuracy: 0.8798070296347347

Classification Report - XGBoost
              precision    recall  f1-score   support

           0       0.84      0.83      0.84      2416
           1       0.92      0.92      0.92      4839

    accuracy                           0.89      7255
   macro avg       0.88      0.88      0.88      7255
weighted avg       0.89      0.89      0.89      7255

**D. SAVE BEST ALGORITHM WITH PICKLE**

In [17]:
if xgb_acc > rf_acc:
    best_model = xgb_model
else:
    best_model = rf_model

with open("best_booking_model.pkl", "wb") as f:
    pickle.dump(best_model, f)

print("Best model saved as 'best_booking_model.pkl'")

Best model saved as 'best_booking_model.pkl'

In [18]:
from joblib import dump
dump(rf_model, 'best_booking_model.pkl', compress=3)

['best_booking_model.pkl']

In [19]:
import pickle
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report


model = RandomForestClassifier(
    n_estimators=10,
    random_state=42
)


model.fit(X_train, y_train)


y_pred = model.predict(X_test)


print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))


with open("best_booking_model.pkl", "wb") as f:
    pickle.dump(model, f)

Accuracy: 0.8926257753273604
              precision    recall  f1-score   support

           0       0.84      0.83      0.84      2416
           1       0.92      0.92      0.92      4839

    accuracy                           0.89      7255
   macro avg       0.88      0.88      0.88      7255
weighted avg       0.89      0.89      0.89      7255